entity: products
topic: "telemetry.ecommerce.products"
target_eps: 20
dynamic_scaling: false

chaos:
  drop_percentage: 0.0
  corrupt_fields: {}

fields:
  product_id:
    type: uuid
    publish_to: products

  vendor_id:
    type: pool
    pool: vendors

  brand_id:
    type: pool
    pool: brands

  category_id:
    type: pool
    pool: categories

  product_name:
    type: product_name

  description:
    type: paragraph

  product_status:
    type: weighted
    values:
      ACTIVE: 80
      DISCONTINUED: 10
      OUT_OF_CATALOG: 10

  created_at:
    type: timestamp

  updated_at:
    type: timestamp

  is_deleted:
    type: weighted
    values:
      "false": 95
      "true": 5
